(()=>{
  const $=id=>document.getElementById(id);
  const drive=x=>{x=String(x||'').trim();const m=x.match(/\/d\/([^/]+)/)||x.match(/[?&]id=([^&]+)/);return m?'https://drive.google.com/uc?export=view&id='+m[1]:x};
  const details=()=>Array.from(document.querySelectorAll('#detailInputs input')).map(x=>drive(x.value)).filter(Boolean).slice(0,10);
  function style(){if($('adminFixCSS'))return;const s=document.createElement('style');s.id='adminFixCSS';s.textContent='.center-post-card{border:1px solid #6d5427;background:linear-gradient(145deg,#17130c,#0d0b08);border-radius:16px;padding:12px;margin:10px 0}.center-post-card.wallet{box-shadow:inset 0 0 35px rgba(93,143,255,.04)}.center-post-card.fancy{box-shadow:inset 0 0 35px rgba(216,180,90,.07)}.fix-copy{margin-left:6px;padding:7px 9px!important;min-width:auto!important;flex:0 0 auto!important}.drive-output{margin-top:8px}.drive-output .linkbox{border-color:#6d5427}.song-test audio{width:100%;margin-top:8px}';document.head.appendChild(s)}
  function rebuildDrive(){const box=$('driveDetails');if(!box)return;box.innerHTML='';for(let i=1;i<=10;i++){const input=document.createElement('input');input.className='input';input.placeholder='Detail Photo '+i+' — Google Drive link';box.appendChild(input)}}
  async function saveProductFixed(){if(typeof window.saveDoc!=='function')return;const name=$('pname')?.value.trim(),show=drive($('pimg')?.value),center=$('pcenter')?.value||'wallet';if(!name||!show)return alert('ပစ္စည်းအမည်နဲ့ Show Photo Link ဖြည့်ပါ');const id=$('pid')?.value||'p-'+Date.now(),old=typeof window.docs==='function'?(await window.docs('products')).find(x=>x.id===id):null;const ds=details();const p={id,name,price:Number($('pprice')?.value||0),center,stock:Number($('pstock')?.value||0),showPhoto:show,image:show,detailPhotos:ds,details:ds,note:$('pnote')?.value.trim()||'',updatedAt:new Date().toISOString(),createdAt:old?.createdAt||new Date().toISOString()};await window.saveDoc('products',id,p);alert((center==='wallet'?'Wallet':'Fancy')+' Shop ထဲကို Product Post တင်ပြီးပါပြီ ✓');$('cancelProduct')?.click();window.refresh?.()}
  function bindPost(){const b=$('saveProduct');if(b)b.onclick=saveProductFixed;const tabs=document.querySelectorAll('.subtab');tabs.forEach(t=>t.addEventListener('click',()=>{setTimeout(()=>{const c=t.dataset.center;$('pcenter').value=c;const h=$('stock')?.querySelector('h3');if(h)h.textContent='➕ Post Product — '+(c==='wallet'?'WALLET SHOP CENTER':'FANCY SHOP CENTER')},0)}));}
  function bindDrive(){const b=$('convertAll');if(!b)return;b.onclick=()=>{const show=drive($('driveShow')?.value),ds=Array.from(document.querySelectorAll('#driveDetails input')).map(i=>drive(i.value)).filter(Boolean).slice(0,10);$('driveShowOut').value=show;$('driveDetailsOut').value=ds.join(', ');$('drivePreview').innerHTML='<div class="drive-output"><div class="linkbox"><b>SHOW PHOTO</b><br>'+show+'</div><div class="linkbox"><b>DETAIL PHOTOS ('+ds.length+'/10)</b><br>'+ds.join(', ')+'</div>'+(show?'<img class="preview" src="'+show+'">':'')+'</div>';};}
  function bindSongTest(){const b=$('testSong');if(!b)return;b.onclick=()=>{const url=$('surl')?.value.trim();if(!url)return alert('Song link ထည့်ပါ');const box=$('songTest');box.innerHTML='';const audio=document.createElement('audio');audio.controls=true;audio.preload='metadata';audio.src=url;box.className='song-test';box.appendChild(audio);const p=document.createElement('p');p.className='small';p.textContent='Loading…';box.appendChild(p);audio.oncanplay=()=>p.textContent='✓ Browser က audio link အဖြစ်ဖတ်လို့ရပါတယ်';audio.onerror=()=>p.textContent='✕ ဒီ URL က direct audio မဟုတ်နိုင်ပါ။ Chatbox.moe ရဲ့ direct audio/file link ကိုထည့်ပါ။';audio.play().catch(()=>{});};}
  function init(){if(!$('dash'))return;style();rebuildDrive();bindPost();bindDrive();bindSongTest();if(!$('detailInputs')?.children.length&&typeof window.makeDetailInputs==='function')window.makeDetailInputs();}
  window.addEventListener('load',()=>setTimeout(init,300));window.addEventListener('style-saan-backend-ready',()=>setTimeout(init,100));new MutationObserver(()=>{if($('dash'))init()}).observe(document.documentElement,{childList:true,subtree:true});
})();