const KEY={products:'style-products',orders:'style-orders',cart:'style-cart',customer:'style-customer'};
const seed=[{id:'w1',center:'wallet',name:'Premium Wallet',price:15000,stock:10,image:'',details:[],note:''},{id:'w2',center:'wallet',name:'Classic Wallet',price:25000,stock:8,image:'',details:[],note:''},{id:'f1',center:'fancy',name:'Fancy Collection',price:18000,stock:12,image:'',details:[],note:''},{id:'f2',center:'fancy',name:'Elegant Gift Set',price:28000,stock:6,image:'',details:[],note:''}];
const read=(k,d)=>JSON.parse(localStorage.getItem(k)||'null')??d,save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let products=read(KEY.products,seed),orders=read(KEY.orders,[]),cart=read(KEY.cart,[]),customer=localStorage.getItem(KEY.customer)||'';
const money=n=>new Intl.NumberFormat('en-US').format(Number(n)||0)+' Ks';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const img=p=>p.image||'https://placehold.co/800x800/17130b/d8b35a?text=STYLE';
function toast(t){const e=document.querySelector('#toast');if(!e)return alert(t);e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function shell(title,content){document.body.innerHTML=`<div class="ambient ambient-a"></div><div class="ambient ambient-b"></div><header class="topbar"><a class="brand" href="shop.html"><img src="https://lh3.googleusercontent.com/d/1bM_UNFnp1L8VyqSkPBIQwfUNdQX0-07J"><span>STYLE</span></a><nav><a href="shop.html">Shop</a><a href="wallet.html">Wallet</a><a href="fancy.html">Fancy</a><a href="cart.html">Cart <b id="cartCount"></b></a><a href="orders.html">Orders</a></nav></header><main class="app-shell"><div class="page-head"><a class="back-btn" href="shop.html">← Back</a><div><span class="eyebrow">STYLE SHOP</span><h2>${title}</h2></div></div>${content}</main><div id="toast" class="toast"></div>`;updateCount()}
function updateCount(){const e=document.querySelector('#cartCount');if(e)e.textContent=cart.reduce((a,x)=>a+x.qty,0)||''}
function cards(list){return list.map(p=>`<article class="product-card"><div class="product-photo-wrap"><img class="product-photo" src="${esc(img(p))}" alt="${esc(p.name)}"></div><div class="product-info"><span class="product-center">${p.center==='wallet'?'WALLET':'FANCY'}</span><h3>${esc(p.name)}</h3><strong>${money(p.price)}</strong><small>Stock ${p.stock}</small><a class="gold-outline" href="product.html?id=${encodeURIComponent(p.id)}">Show Photo / Order</a></div></article>`).join('')||'<div class="empty">ပစ္စည်းများ မရှိသေးပါ။</div>'}
function home(){shell('Shop Center',`<section class="flow-card intro-card"><img class="main-logo" src="https://lh3.googleusercontent.com/d/1bM_UNFnp1L8VyqSkPBIQwfUNdQX0-07J"><span class="eyebrow">WELCOME TO STYLE</span><h1>သင့် Style ကို<br><em>ရွေးချယ်ပါ</em></h1><p>Shop Center တစ်ခုရွေးပြီး သီးသန့် page နဲ့ ကြည့်နိုင်ပါတယ်။</p><label class="field-label">Customer Name</label><input id="customer" class="input" value="${esc(customer)}" placeholder="နာမည် ရိုက်ထည့်ပါ..."><div class="center-grid compact"><a class="center-card" href="wallet.html" onclick="rememberCustomer()"><span class="card-icon">◈</span><strong>Wallet Shop Center</strong><small>Wallet Collection</small><i>ဝင်မည် →</i></a><a class="center-card" href="fancy.html" onclick="rememberCustomer()"><span class="card-icon">✦</span><strong>Fancy Shop Center</strong><small>Fancy Collection</small><i>ဝင်မည် →</i></a></div></section>`)}
function rememberCustomer(){const e=document.querySelector('#customer');if(e&&e.value.trim())localStorage.setItem(KEY.customer,e.value.trim())}
function centerPage(center){const name=center==='wallet'?'Wallet Shop Center':'Fancy Shop Center';shell(name,`<div class="flow-card"><div class="filters"><a class="filter active" href="${center}.html">${center==='wallet'?'◈ Wallet':'✦ Fancy'}</a><a class="filter" href="shop.html">All Products</a><a class="filter" href="cart.html">Cart</a></div><div class="product-grid">${cards(products.filter(p=>p.center===center))}</div></div>`)}
function productPage(){const p=products.find(x=>x.id===new URLSearchParams(location.search).get('id'));if(!p)return home();shell('Product Detail',`<section class="flow-card"><div class="detail-images">${[p.image,...(p.details||[])].filter(Boolean).map(u=>`<img src="${esc(u)}" alt="${esc(p.name)}">`).join('')||`<img src="${esc(img(p))}" alt="${esc(p.name)}">`}</div><span class="eyebrow">${p.center==='wallet'?'WALLET':'FANCY'}</span><h2>${esc(p.name)}</h2><div class="detail-price">${money(p.price)}</div><p class="detail-note">${esc(p.note||'Premium Style collection item.')}</p><div class="qty-row"><button onclick="changeQty(-1)">−</button><strong id="qty">1</strong><button onclick="changeQty(1)">+</button></div><button class="gold-outline" onclick="addCart('${p.id}')">Add to Cart</button><button class="gold-btn" onclick="buyNow('${p.id}')">Order Now →</button></section>`);window.currentProduct=p;window.currentQty=1}
function changeQty(n){window.currentQty=Math.max(1,Math.min(window.currentProduct?.stock||1,window.currentQty+n));document.querySelector('#qty').textContent=window.currentQty}
function addCart(id,qty=window.currentQty||1){const p=products.find(x=>x.id===id);if(!p)return;if(p.stock<qty)return toast('Stock မလုံလောက်ပါ။');const old=cart.find(x=>x.id===id);if(old){if(old.qty+qty>p.stock)return toast('Stock မလုံလောက်ပါ။');old.qty+=qty}else cart.push({...p,qty});save(KEY.cart,cart);updateCount();toast('Cart ထဲထည့်ပြီးပါပြီ ✦')}
function buyNow(id){addCart(id);location.href='cart.html'}
function cartPage(){const sub=cart.reduce((a,x)=>a+x.price*x.qty,0);shell('Shopping Cart',`<section class="flow-card"><div id="cartList">${cart.length?cart.map(x=>`<div class="cart-row"><div><b>${esc(x.name)}</b><small>${money(x.price)} × ${x.qty}</small></div><div class="cart-actions"><button onclick="cartMinus('${x.id}')">−</button><b>${x.qty}</b><button onclick="cartPlus('${x.id}')">+</button><button class="remove" onclick="cartRemove('${x.id}')">×</button></div></div>`).join(''):'<div class="empty">Cart ထဲမှာ ပစ္စည်းမရှိသေးပါ။</div>'}</div><div class="invoice"><div><span>Subtotal</span><b>${money(sub)}</b></div><div class="invoice-total"><span>Total</span><b>${money(sub)}</b></div></div>${cart.length?'<a class="gold-btn" href="checkout.html">Checkout →</a>':'<a class="gold-btn" href="shop.html">Shop Now →</a>'}</section>`)}
function rerenderCart(){save(KEY.cart,cart);cartPage()}
function cartPlus(id){const x=cart.find(a=>a.id===id),p=products.find(a=>a.id===id);if(x&&p&&x.qty<p.stock)x.qty++;else toast('Stock မလုံလောက်ပါ။');rerenderCart()}
function cartMinus(id){const x=cart.find(a=>a.id===id);if(!x)return;if(--x.qty<=0)cart=cart.filter(a=>a.id!==id);rerenderCart()}
function cartRemove(id){cart=cart.filter(a=>a.id!==id);rerenderCart()}
function checkoutPage(){if(!cart.length)return location.href='cart.html';const sub=cart.reduce((a,x)=>a+x.price*x.qty,0),discount=sub>=10000?Math.floor(sub/10000)*500:0,total=sub-discount;shell('Checkout',`<section class="flow-card"><div class="invoice"><div><span>Subtotal</span><b>${money(sub)}</b></div><div><span>Discount</span><b>-${money(discount)}</b></div><div class="invoice-total"><span>Total</span><b>${money(total)}</b></div></div><input id="phone" class="input" placeholder="ဖုန်းနံပါတ်"><select id="delivery" class="input"><option value="pickup">Pick-up လာယူမည်</option><option value="delivery">Delivery ပို့မည်</option></select><textarea id="address" class="input" placeholder="Delivery လိပ်စာ"></textarea><select id="payment" class="input"><option value="cash">Cash</option><option value="online">Online Payment</option></select><textarea id="note" class="input" placeholder="Order Note"></textarea><button class="gold-btn" onclick="submitOrder(${sub},${discount},${total})">Confirm Order ✓</button></section>`)}
function submitOrder(sub,discount,total){const delivery=document.querySelector('#delivery').value,phone=document.querySelector('#phone').value.trim(),address=document.querySelector('#address').value.trim();customer=localStorage.getItem(KEY.customer)||prompt('Customer Name ရိုက်ထည့်ပါ')||'Customer';localStorage.setItem(KEY.customer,customer);if(delivery==='delivery'&&(!phone||!address))return toast('Delivery အတွက် ဖုန်းနဲ့ လိပ်စာ ဖြည့်ပါ။');const code='ORD-'+Math.floor(1000+Math.random()*9000);const order={id:Date.now().toString(),orderCode:code,customerName:customer,items:cart.map(x=>({id:x.id,name:x.name,price:x.price,qty:x.qty})),subtotal:sub,discount,totalAmount:total,deliveryType:delivery,phone,address,paymentType:document.querySelector('#payment').value,note:document.querySelector('#note').value.trim()||'မရှိပါ',status:'order စစ်ဆေးနေဆဲ',adminNote:'',createdAt:new Date().toISOString()};orders.unshift(order);cart.forEach(x=>{const p=products.find(a=>a.id===x.id);if(p)p.stock=Math.max(0,p.stock-x.qty)});save(KEY.orders,orders);save(KEY.products,products);cart=[];save(KEY.cart,cart);location.href='success.html?code='+encodeURIComponent(code)}
function successPage(){const o=orders.find(x=>x.orderCode===new URLSearchParams(location.search).get('code'));shell('Order Received',`<section class="flow-card success-card"><div class="success-icon">✓</div><span class="eyebrow">ORDER RECEIVED</span><h2>Order တင်ပြီးပါပြီ</h2><p>Order Code</p><strong class="detail-price">${esc(o?.orderCode||'')}</strong><p>${esc(o?.customerName||customer)}</p><p>Total: <b>${money(o?.totalAmount)}</b></p><a class="gold-btn" href="orders.html">Order Status ကြည့်မည် →</a><a class="gold-outline" href="shop.html">Continue Shopping</a></section>`)}
function ordersPage(){shell('Order Checker',`<section class="flow-card"><input id="code" class="input" placeholder="Order Code (ဥပမာ ORD-1234)"><button class="gold-btn" onclick="checkOrder()">Check Order →</button><div id="result" class="hidden"></div></section>`)}
function checkOrder(){const code=document.querySelector('#code').value.trim(),o=orders.find(x=>x.orderCode===code),r=document.querySelector('#result');if(!o)return toast('Order Code မတွေ့ရှိပါ။');r.className='order-result';r.innerHTML=`<span class="eyebrow">ORDER ${esc(o.orderCode)}</span><h3>${esc(o.customerName)}</h3><p>Status: <b>${esc(o.status)}</b></p><p>Total: <b>${money(o.totalAmount)}</b></p><p>Admin Note: ${esc(o.adminNote||'မရှိပါ')}</p>`}
function init(){const p=location.pathname.split('/').pop().toLowerCase();if(p==='wallet.html')centerPage('wallet');else if(p==='fancy.html')centerPage('fancy');else if(p==='product.html')productPage();else if(p==='cart.html')cartPage();else if(p==='checkout.html')checkoutPage();else if(p==='success.html')successPage();else if(p==='orders.html')ordersPage();else home()}
window.addEventListener('DOMContentLoaded',init);